/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Pay,
  IERC20PayInterface,
} from "../../../contracts/SwapCallback.sol/IERC20Pay";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20Pay__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20PayInterface {
    return new Interface(_abi) as IERC20PayInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC20Pay {
    return new Contract(address, _abi, runner) as unknown as IERC20Pay;
  }
}
