/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoolViewForCallback,
  IPoolViewForCallbackInterface,
} from "../../../contracts/SwapCallback.sol/IPoolViewForCallback";

const _abi = [
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPoolViewForCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolViewForCallbackInterface {
    return new Interface(_abi) as IPoolViewForCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPoolViewForCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPoolViewForCallback;
  }
}
