/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUniswapV3PoolSwapMinimal,
  IUniswapV3PoolSwapMinimalInterface,
} from "../../../contracts/SwapCallback.sol/IUniswapV3PoolSwapMinimal";

const _abi = [
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUniswapV3PoolSwapMinimal__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV3PoolSwapMinimalInterface {
    return new Interface(_abi) as IUniswapV3PoolSwapMinimalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUniswapV3PoolSwapMinimal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUniswapV3PoolSwapMinimal;
  }
}
