/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUniswapV3FactoryMinimal,
  IUniswapV3FactoryMinimalInterface,
} from "../../../contracts/interfaces/IUniswapV3FactoryMinimal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    name: "createPool",
    outputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    name: "getPool",
    outputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUniswapV3FactoryMinimal__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV3FactoryMinimalInterface {
    return new Interface(_abi) as IUniswapV3FactoryMinimalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUniswapV3FactoryMinimal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUniswapV3FactoryMinimal;
  }
}
