/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWETH9Minimal,
  IWETH9MinimalInterface,
} from "../../../contracts/interfaces/IWETH9Minimal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "guy",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IWETH9Minimal__factory {
  static readonly abi = _abi;
  static createInterface(): IWETH9MinimalInterface {
    return new Interface(_abi) as IWETH9MinimalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWETH9Minimal {
    return new Contract(address, _abi, runner) as unknown as IWETH9Minimal;
  }
}
